### ISSUE TITLE
Creazione nuova zona

### ISSUE THREAD

**Issue by ikatsukoi** [OnosTeam/onos#22]
Per creare una nuova zona si clicka sul pulsante nuova sul menù destro a comparsa una volta ckickato il pulsante si viene reindirizzati ad una nuova pagina ? 

se si una volta clickato sul submit sarebbe utile essere reindirizzati alla pagina con la lista delle zone

**Comment by onosAdmin** [comment]
Si va bene si puó fare ma il pulsante destro dove?in qualsiasi posizione ci si trovi?forse ha piú senso che si possa creare nuove zone solo quando si è sulla lista zone..oppure il menú dx è sempre uguale e disponibile in ogni pagina?

**Comment by onosAdmin** [comment]
Ops correggo:
Si va bene si puó fare ma il menu destro dove?in qualsiasi posizione ci si trovi?forse ha piú senso che si possa creare nuove zone solo quando si è sulla lista zone..oppure il menú dx è sempre uguale e disponibile in ogni pagina?

**Comment by ikatsukoi** [comment]
scusa non sono stato chiaro io ... il menù laterale è accessibile e compare soltanto quando è strettamente necessario ad esempio nella lista zone compare e ti permette di creare o eliminare le zone e contiene il tasto submit

**Comment by onosAdmin** [comment]
Perfetto ora ho capito :+1:

**Comment by onosAdmin** [comment]
Implementato in 5.29
