### ISSUE TITLE
standardidazzione nome files

### ISSUE THREAD

**Issue by onosAdmin** [OnosTeam/onos#27]
Rinominare i files html ,css e fonts in modo che seguano questa specifica:

home --> pagina home  al momento mostra la lista delle zone

display_zone_objects   --> pagina che mostra la lista degli oggetti in una zona

scenarios_list  --> pagina che mostra la lista degli scenari

mod_scenario --> pagina per modificare uno scenario

login --> pagina di login

**Comment by ikatsukoi** [comment]
c'è un piccolo problema 

home è una nuova pagina di onos in cui si riassumeranno delle cose che per il momento decidiamo noi ma in futuro mi piacerebbe fosse a discrezione dell'utente 

mentre la pagina che mostra la lista delle zone la chiamerei zone list (non si possono utilizzare gli oggetti se sono al di fuori di una zona )

**Comment by onosAdmin** [comment]
Si va bene  chiamiamolo  zone_list anche se per adesso è in home..

**Comment by ikatsukoi** [comment]
ok sistemati i nomi
