### ISSUE TITLE
zona automatica originale 

### ISSUE THREAD

**Issue by ikatsukoi** [OnosTeam/onos#28]
quando un nuovo oggetto viene acceso e comunica con onoscenter per la prima volta e non è stata creata nessuna stanza (nel caso del primo avvio) si potrebbe creare una zona in automatico (automatic_zone) nella quale vengono assegnati tutti i nuovi oggetti collegati ad onoscenter

**Comment by onosAdmin** [comment]
Funziona già così ! viene creata una zona con il seriale del nodo e vengono creati tutti gli oggetti ed assegnati a quella zona..
