### ISSUE TITLE
cose da aggiungere alla grafica

### ISSUE THREAD

**Issue by onosAdmin** [OnosTeam/onos#8]
Cose da aggiungere alla grafica:

-La parte in basso della pagina web deve poter contenere un log del sistema e di tutte le azioni che esso compie, cambio stati oggetti , cambio stati da mail ecc
questo log deve essere minimizzabile..

**Comment by ikatsukoi** [comment]
io sconsiglio vivamente di mettere qualcosa sul fondo della pagina web mobile ... ci prendi dentro scorrendo la pagina ... piuttosto metterei un riquadro nella pagina home con l'ultimo cambiamento avvenuto e se ci clicchi sopra ti si apre una pagina con il log (ho appena capito a cosa servono le issues XD )

**Comment by onosAdmin** [comment]
Ok proviamo come dici tu...ma deve avere comunque una certa rilevanza...secondo me è comodo vedere 3 o 4 azioni compiute da onos...ed è comodo vedere cosa sta facendo onos dopo che hai premuto un pulsante..ma per adesso prevediamolo solo sulla home.
